service: swipe-thought-bot
app: swipe-thought-bot
org: toporok

provider:
  name: aws
  runtime: python3.8
  stage: ${opt:stage, '${file(./serverless.env.yml):SLS_STAGE, ''}'}
  region: ${file(./serverless.env.yml):AWS_REGION, ''}
  profile: ${file(./serverless.env.yml):AWS_PROFILE, ''}
  environment:
    TELEGRAM_TOKEN: ${self:custom.TELEGRAM_TOKEN}

custom:
  TELEGRAM_TOKEN: ${file(./serverless.env.yml):TELEGRAM_TOKEN, ''}

functions:
  webhook:
    handler: handler.webhook
    package:
      artifact: # https://github.com/serverless/serverless/issues/6752#issuecomment-586960000
    events:
      - http: POST /

  set_webhook:
    handler: handler.set_webhook
    package:
      artifact: # https://github.com/serverless/serverless/issues/6752#issuecomment-586960000
    events:
      - http: POST /set_webhook

plugins:
  - serverless-python-requirements

resources:
  Resources:
    ElasticSearchDomainSmall:
      Type: 'AWS::Elasticsearch::Domain'
      Properties:
        DomainName: es-small-${self:service}-${self:provider.stage}
        ElasticsearchVersion: '7.9'
        ElasticsearchClusterConfig:
          ZoneAwarenessEnabled: false
          InstanceCount: 1
          InstanceType: t2.small.elasticsearch
        EBSOptions:
          EBSEnabled: true
          VolumeType: gp2
          VolumeSize: 10
