service: swipe-thought-bot
app: swipe-thought-bot
org: toporok

provider:
  name: aws
  runtime: python3.8
#  stage: ${opt:stage, 'dev'}
  region: ${file(./serverless.env.yml):AWS_REGION, ''}
  profile: ${file(./serverless.env.yml):AWS_PROFILE, ''}
  environment:
    TELEGRAM_TOKEN: ${file(./serverless.env.yml):TELEGRAM_TOKEN, ''}

functions:
  webhook:
    handler: handler.webhook
    events:
      - http: POST /

  set_webhook:
    handler: handler.set_webhook
    events:
      - http: POST /set_webhook

plugins:
  - serverless-python-requirements
