service: swiper-common
app: swipe-thought-bot
org: toporok

#frameworkVersion: '2.16.1'

provider:
  name: aws

  region: us-east-1
  stage: common
  profile: ${file(./serverless.env.yml):PROFILE, ''}

  # https://www.serverless.com/framework/docs/deprecations/#LAMBDA_HASHING_VERSION_V2
  lambdaHashingVersion: 20201221

custom:
  constants:
    SERVICE_SHORT_NAME: stb

resources:
  Resources:
    ElasticSearchDomainSmall:
      Type: 'AWS::Elasticsearch::Domain'
      Properties:
        DomainName: es-small-${self:custom.constants.SERVICE_SHORT_NAME}
        ElasticsearchVersion: '7.9'
        ElasticsearchClusterConfig:
          ZoneAwarenessEnabled: false
          InstanceCount: 1
          InstanceType: t2.small.elasticsearch
        EBSOptions:
          EBSEnabled: true
          VolumeType: gp2
          VolumeSize: 10
